#virtual host listening to the http then down below redirect to the https
<VirtualHost *:80>
    ServerName secure.nick-maharjan.sasm.uclllabs.be
    DocumentRoot /var/www/html
    Redirect permanent / https://secure.nick-maharjan.sasm.uclllabs.be/
</VirtualHost>

#configuring for https and it listens to https requests and server content for ssl
<VirtualHost *:443>
    ServerName secure.nick-maharjan.sasm.uclllabs.be
    DocumentRoot /var/www/html

    SSLEngine on
	#it is used to encrypt communication
    SSLCertificateFile /etc/pki/fullchain.pem
	# This points to the private key for ssl certificate
    SSLCertificateKeyFile /etc/pki/nick-maharjan.sasm.uclllabs.be.key
	#It enables mod_rewrite for url rewriting
    <IfModule mod_rewrite.c>
        RewriteEngine on
	#checks the request is no http or something
        RewriteCond %{HTTPS} off
	#rewrutes the url then redirect to https, preserving host and URI.
        RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]
    </IfModule>
</VirtualHost>
