# same as secure
<VirtualHost *:80>
    ServerName supersecure.nick-maharjan.sasm.uclllabs.be
    DocumentRoot /var/www/html
    RewriteEngine On
    RewriteRule ^ https://supersecure.nick-maharjan.sasm.uclllabs.be%{REQUEST_URI} [L,R=301]
</VirtualHost>

<VirtualHost *:443>
    ServerName supersecure.nick-maharjan.sasm.uclllabs.be
    DocumentRoot /var/www/html

    SSLEngine on
    SSLCertificateFile /etc/pki/fullchain.pem
    SSLCertificateKeyFile /etc/pki/nick-maharjan.sasm.uclllabs.be.key
    
# header ensures site communicate with only https and it will enforce for 1 year
    Header always set Strict-Transport-Security "max-age=31536000"
</VirtualHost>
